1	x	neu	Philip	Vanessa	04.06.1987			TV 	Neckarau	2
2	x	neu	Grund	Stephanie	08.07.1987			TV	Neckarau	3
3	x	2	Umminger	Bettina	11.12.1986	0	N	TSG	Heilbronn	4
4	x	neu	Wukkert	Ellen	25.11.1987			TV	Mosbach	5
		0	Klein	Jasmin 			S	SSV Waghäusel		0
		4	Zang	Isabell	03.07.1987	1	n		FC Rot	1
		12	Billmaier	Lena	87	1	n	TSG	Wiesloch	6
		9	Götze	Stephanie	1987	1	n	SpVgg	Ketsch	7
		8	Sutera	Celine	87	1	n	SpVgg	Ketsch	10
		3	Gruschka	Katja-Amelie	21.02.1986	0	N	TSG	Heilbronn	
		0	Theil	Alexandra			S	SSV Waghäusel		
		1	Lüdtke	Franziska	10.08.1987	1	s		Spfr.Neusatz	
		1	Schäfer 	Sigrid	17.02.1986	0	N	TV	Bad Rappenau	
		5	Börkel	Jessica	16.12.1987	1	n	BC	Viernheim	
		6	Wollburg	Isabell	23.06.1987	1	n	SV	Ketsch	
		7	Adler	Michaela	08.12.1987	1	n	BC	Viernheim	
		10	Fischer 	Marie	12.03.1987	1	n	TV	Bad Rappenau	
		11	Heinl	Sarah	24.05.1987	1	n	TSV	Birkenau	
		1	Schlechter	Maren	07.08.1986	0	S	Post Südstadt Karlsruhe		
		2	Bounin	Laura	09.12.1986	0	S	Post Südstadt Karlsruhe		
		3	Kleine	Silvia	24.07.1986	0	S	Post Südstadt Karlsruhe		
		4	Woschek	Nathalie	08.12.1986	0	S	KTV 1846		
		5	Arnold	Franziska	?	0	S	Spfr.	Neusatz	
		6	Böhme	Jennifer	25.08.1987	1	s		TV Mörsch	
		7	Windisch	Sandra	10.01.1987	1	s		TV Mörsch	
		8	Gensow	Svenia	09.10.1987	1	s		TSG Bruchsal	
	1	Fuchs	Mona	19.01.1995	2	S	SSV	Waghäusel
	2	Käpplein	Lara	26.05.1995	2	s	SSV	Waghäusel
1	x	3	Braun	Jennifer	29.08.1992	0	n	TV	Bad Rappenau	1
2	x	6	Sommer	Nadine	25.01.1993	1	N	TV 	Bad Rappenau	2
3	x	8	Klein	Jana	25.5.93	1	N	TSG 	Wiesloch	3
		0	Wiedemann	Eva	05.11.1992	0	s	SSV 	Waghäusel	
		1	Gummert	Steffi	30.01.1992	0	n	TV	Bad Rappenau	
		1	Knippscheer	Lisa	19.03.1992	0	s	Spfr. 	Neusatz	
		2	Wollburg	Lisa	8.2.92	0	n	SpVgg	06 Ketsch	
		2	Nollau	Saskia	02.08.1992	0	s	BC	 Schöllbronn	
		3	Kühner	Jenny	17.02.1992	0	s	TSG	 Bruchsal	
		4	Aenis	Lisa	29.06.1992	0	n	TSG	Wiesloch	
		4	Ristucci	Rachel		?	s	Post	 Südstadt Karlsruhe	
		5	Fischer	Corinna		?	s	Spfr. 	Neusatz	
		6	Karcher	Teresa	29.01.1993	1	S	BC	Schöllbronn	
		7	Gehring	Benita	02.04.1993	1	N	TV 	TV Bad Rappenau	
		7	Stindl	Lorena	09.05.1993	1	S	BSC	Waghäusel	
		9	Fath	Mareike	29.05.1992	0	N	TV 	Gorxheim	
	u15	1	Zang	Lena	06.06.1993	1	N	FC	 Rot	
		5	Söbbing	Anna-Lena	18.01.1993	1	N	TV 	Bad Rappenau	
1	x	1	Winter	Svenja	21.05.1990	0	N	FC	Rot	1
2	x	2	Braun	Valeska	08.03.1990	0	N	SG	Hemsbach	2
3	x	6	Zimmermann	Julia	29.08.1991	1	n	TSG	Dossenheim	3
4	x	neu	Opitz	Vanessa	09.09.1990			TV	Mosbach	5
5	x	neu	Biber	Nadja	27.06.1990			FC	Rot	6
6	x	13	Kubosch	Sarah	29.08.1990	0	N	TV 	BadRappenau	8
7	x	u13	Zang	Lena	06.06.1993			FC	Rot	9
8	x	u13	Söbbing	Anna-Lena	18.01.1993			TV	Bad Rappenau	10
9	x	4	Maßalski	Nicole	20.07.1990	0	N	FC	Rot	11
10	x	neu	Bauer	Janina	31.07.1991			TV	Lauffen	12
11	x	neu	Kolovou	Vasilia	12.07.1991			TV	Lauffen	13
12	x	neu	Bayer	Miriam	27.05.1991			TSG	Heilbronn	14
13	x	neu	Reinhardt	Pia	13.06.1991			TSG	Heilbronn	15
14	x	neu	Scholl	Janina	03.09.1991			TV	Lauffen	16
15	x	neu	Luttert	Simone	17.01.1991			TSG	Dossenheim	
16	x	7	Schmitt	Ramona	15.06.1991	1	n	TSG	Wiesloch	
		neu	Emmler	Sarah	08.06.1990			SG	Hemsbach	4
		u13	Wollburg	Lisa	08.02.1992	0	n	SpVgg	06 Ketsch	7
		10	Brain	Alisa	91	1	N	TSG	Wiesloch	
		11	Hauck	Lisa	91	1	N	TSG	Wiesloch	
		12	Berli	Amelie	91	1	N	TSG	Wiesloch	
		8	Häuser	Maren	1991	1	n	TSG	Wiesloch	
		neu	Janositz	Eva-maria	03.03.1990			TSG	Heilbronn	
		5	Lissek-Hör	Caroline	11.03.1990	O 	N	TSV	Birkenau	
		14	Altuna	Ceyda	12.03.1990	0	N	FC	Rot	
		16	Gramlich	Daniela	08.05.1990	0	N	TSV	Birkenau	
		15	Wetzel	Sarah	24.05.1990	0	n	TV	Gorxheim	
		0	Fillinger	Nadine	05.06.1990	1	S		SSV Waghäusel	
		3	Moog	Michelle	13.06.1990	0	N	1.BC	Viernheim	
		0	Nolze	Stella	16.07.1990	1	N	TSG	Dossenheim	
		0	Oestreicher	Nicole	08.02.1991	1	s	SSV 	Waghäusel	
		1	Sondey	Sophia	04.05.1991	1	s	BSC	Waghäusel	
		2	Kulzer	Lisa	30.05.1991	1	s	BSC	Waghäusel	
		9	Jungmann	Christina	05.08.1991	!	N	TV	Gorxheim	
1	x		4	Wirnitzer	Jacquline	07.10.1988	0	n	SG	Hemsbach	1
2	x		3	Nechita	Madalina	08.06.1988	0	n	TSG	Dossenheim	2
3	x		5	Müller	Corinna	24.08.1988	0	n	TSG	Wiesloch	3
4	x		7	Kilian	Alexandra	04.07.1989	1	N	TSG	Wiesloch	4
5	x		6	Knobel	Leonie	22.09.1988	0	n	TSG	Heilbronn	5
6	x		neu	Panzilios	Elena	30.06.1989			TV	Mosbach	6
7	x		neu	Wallner	Kathrin	31.05.1988			BC	Viernheim	7
8	x		8	Wittemann	Carolin	26.08.1989	1	N	FC	Rot	8
9	x		neu	Okutan	Elif				BC	Viernheim	10
10	x		neu	Kögelmeier	Ariane	14.12.1988			SV	Leingarten	11
11	x		10	Finsterle	Svenja	21.10.1989	1	N	TSG	Wiesloch	12
12	x		neu	Finsterle	Julia	21.10.1989			TSG	Wiesloch	13
13	x			Kulakov	Katharina	0.1989			TSG	Wiesloch	
14	x			Maier	Britta	09.05.1988					
			neu	Bechtel	Lisa	10.08.1989			TSG	Wiesloch	9
			0	Schäfer	Stefanie			s		SSV Waghäusel	
			0	Hauck 	Sabrina			s		SSV Waghäusel	
			0	Arns	Stefanie			s		SSV Waghäusel	
				Thumfahrt	Melanie	15.09.1989	1	N	TV	Bad Rappenau	
			0	Oestreicher	Desiree	30.07.1989	1	S		SSV Waghäusel	
			1	Ghebrab	Semy	1988	0	n	TV 	Waldhof	
			2	Hermes	Jennifer	09.09.1988	0	n	FC	Rot	
			9	Eckstein	Emilie	27.06.1989	1	N	TSG	Wiesloch	
			1	Laub	Lena	24.05.1988	0	s		BC Schöllbronn	
			2	Endemann	Nicole	10.08.1988	0	s	Spfr.	Neusatz	
			3	Linder	Mona	08.07.1988	0	s		Post Südstadt Karlsruhe	
			4	Weikard	Carolin	27.07.1989	1	S	FC	Rot	
			5	Stadler	Lena	17.03.1989	1	S	SSV	Waghäusel	
			6	Müller	Sina	20.02.1989	1	S		TV Pforzheim	
			7	Werner	Anna	21.09.1989	1	S		Badminton Sportfreunde Neusatz-Bad Herrenalb	
			8	Bartelt	Isabell	06.11.1989	1	S		Badminton Sportfreunde Neusatz-Bad Herrenalb	
			9	Schwenk	Iris	04.02.1989	1	S		BSC Waghäusel	
			10	Straub	Dorothea	05.08.1989	1	S		TV Pforzheim	
			11	Herberger	Elena	17.06.1989	1	S		BSC Waghäusel	
