1	x	2	Rica	matthias	03.03.1994	N	0	SpVgg	Ketsch
2	x	3	Zimmermann	Rico	11.07.1996	N	2	TSG	Dossenheim
		neu	Stein	Oliver	13.06.1994	N	?	F96	Schwetzingen
		1	Roth	Fabian	01.01.1996	S	2	Spfr.	Neusatz
1	x	1	Wieland	Alexander	05.01.1992	N	0	TSG	Heilbronn	1
2	x	3	Horsinka	Kevin	1992	N	0	TV	Bad Rappenau	2
3	x	4	Hertinger	Markus	26.08.1992	N	0	SG	Hemsbach	4
4	x	8	Häuser	Jannik	14.07.1993	N	1	TSG 	Wiesloch	5
5	x	9	Haußmann	Philipp	31.12.1993	N	1	TV	Bad Rappenau	6
6	x	10	Philipp	Alexander	1993	N	1	SpVgg 06	Ketsch	7
7	x	neu	Beck	Alexander	01.06.1993			SV	Leingarten	8
8	x	neu	Yannic	Arnold	1993			TV	Bad Rappenau	9
9	x	neu	Kücükdüner	Alper	15.08.1992			SpVgg 06	Ketsch	10
10	x	neu	Schaul	Alessandro	10.10.1992			SV	Leingarten	11
11	x	neu	Bernd	Heiko	10.05.1992			SG	Hemsbach	12
12	x		Brill	Stephan	14.03.1993			SG	Hemsbach	
13	x	neu	Lang	Dennis	11.11.1992			SV	Leingarten	
14	x	6	Lang	Stephan	15.04.1992	N	0	TSG	Heilbronn	
15	x	neu	Schneider	Tobias				TV	Neckarau	
		2	Leide	Daniel	25.12.1992	N	0	SG	Hemsbach	3
		7	Dotterer 	Marc	27.07.1993	N	1	TV	Bad Rappenau	5
		neu	Krummradt	Simon	02.11.1993			TSG	Dossenheim	13
		7	Ostojic	Marcel	?	S	?		TV Mörsch	
		12	Lindemaier	Christian	17.10.1993	N 	1	 TV 	Bad Rappenau	
		11	Arnold	Yannic	17.09.1993	N	1	TV Bad Rappenau		
		11	Röckinger	Matthias	06.06.1993	S	1	TV	Pforzheim	
		13	Wetzel	Sebastian	14.05.1993	N	1	TV	Gorxheim	
		8	Werle	Nicolas	02.05.1993	S	1	BSC	Waghäusel	
		9	Heiler	Alexander	28.04.1993	S	1	SSV	Waghäusel	
		1	Notheisen	Tobias	12.02.1993	S	0	SSV	Waghäusel	
		10	Gahler	Florian	06.01.1993	S	1	TV	Pforzheim	
		1	Roth	Sebastian	15.10.1992	S	0	Spfr.	Neusatz-Bad Herrenalb	
		4	Göbel	Stefan	31.05.1992	S	0		SSV Waghäusel	
		5	Rössling	Paul	22.05.1992	N	0	SG	Hemsbach	
		5	Wolny	Alexander	30.04.1992	S	0	BSC	Waghäusel	
		2	Karl	Grischa	10.04.1992	S	0	Post 	Südstadt Karlsruhe	
		3	Werner	Oliver	23.02.1992	S	0		SSV Waghäusel	
		6	Fettig	Christian	09.01.1992	S	0	BSC	Waghäusel	
		14	Schäfer	Simon	92	N	0	TSG	Wiesloch	
1	x	2	Schmitt	Christian	31.07.1990	0	N	SG	Hemsbach	1	
2	x	4	Zerzawy	Mauritz	17.07.1990	0	N	TV	Bad Rappenau	2	
3	x	3	Rößling	Christoph	13.07.1990	0	N	SG	Hemsbach	2	
4	x	5	Haas	Stefan	08.09.1990	0	N	SG	Hemsbach	3	
5	x	10	Gross	Benjamin	20.09.1991	1	N	TSG	Dossenheim	4	
6	x	6	Salewski	Christian	03.07.1990	0	N	SG	Hemsbach	5	
7	x	11	Hartmann	Timo	04.03.1991	1	N	SG	Hemsbach	6	
8	x	14	Weber	Timo	17.02.1991	1	N	SG 	Hemsbach	7	
9	x	12	Maibach	Florian	04.06.1991	1	N	Fortruna 96	Schwetzingen	8	
10	x	neu	Reinemuth	Heiko	20.03.1991			SG	Hemsbach	9	
11	x	15	Nüßlein	Jürgen	10.10.1991	1	N	TSG	Heilbronn	10	
12	x	neu	Samhammer	Christoph	02.11.1990			SG	Hemsbach	11	
13	x	20	Stübe	Marc	11.01.1990	0	N	SpVgg	Ketsch	12	
14	x	13	Söbbing	Maximilian	15.12.1991	1	N	TV	Bad Rappenau	13	
15	x	neu	Hoffmann	Marco	02.07.1990			TV	Neckargmünd	14	
16	x	neu	Umminger	Markus	11.03.1990			TSG	Heilbronn	15	
17	x	neu	Däuber	Lukas	30.11.1990			TV	Neckargmünd	16	
18	x	neu	Tropf	Kevin	08.07.1991			FC	Rot	18	
19	x	neu	Matern	Anton	09.03.1990			TSG	Heilbronn	19	
20	x	neu	Mächtel	Michael	21.02.1991			FC	Rot	20	
21	x	neu	Walter	Jan	?.?.1991			SG	Hemsbach	22	
22	x	neu	Albert	Sascha	15.08.1990			FC	Rot	23	
23	x	neu	Hess	Rene	03.09.1990			TV	Neckargmünd	24	
24	x	neu	Bender	Frank	11.03.1991			FC	Rot	25	
25	x	neu	Laabs	Jonas	26.04.1991			TSG	Heilbronn	26	
26	x	neu	Tremmel	Timo	30.05.1991			SV	Leingarten	27	
27	x	neu	Ludwig	Michael	03.04.1991			TV	Neckargmünd	28	
28	x	neu	Mögle	Marvin	08.11.1991			TSG	Heilbronn	29	
29	x		Siefert	Sven	22.11.1991			TSG	Wiesloch		
30	x		Hort	Sebastian	11.10.1991			TV	Ma-Waldhof		
31	x		Gross	Marco	30.07.1991			TV	Ma-Waldhof		
32	x		Spindler	Christian	19.01.1991			TV	Ma-Waldhof		
33	x		Ulrich	Benjamin	16.01.1990			TV	Bad Rappenau		
34	x		Stoll	Nico				TV	Neckarau		
		neu	Stein	Kevin	16.06.1991			Fortruna 96	Schwetzingen	17	
		neu	Schneider	Tobias	29.10.1991			TV	Neckarau	21	
		8	Grüber	Eike	05.12.1991	1	N	TSG	Dossenheim		
		18	Petschenka	Adrian	29.10.1991	1	N	TSV	Gorxheim		
		5	Benz-Baldas	Felix	27.09.1991	1	S	Post 	Südstadt Karlsruhe		
		6	Benz-Baldas	Jonas	27.09.1991	1	S	Post 	Südstadt Karlsruhe		
		7	Vardar	Bülent	06.07.1991	1	S	Spfr.	Neusatz-Bad Herrenalb		
			Roth	Patrick	15.04.1991	1	s	Spfr.	Neusatz-Bad Herrenalb		
		9	Mühlbauer	Jan	14.02.1991	1	N	TSG	Dossenheim		
		0	Burkhard	Felix	17.01.1991	0	n	TSG	Dossenheim		
		3	Notheisen	Timo	21.10.1990	0	S		SSV Waghäusel		
		2	Machauer	Marc	12.09.1990	0	S		SSV Waghäusel		
		1	Sickinger	Matthias	17.08.1990	0	S	ssv	SSV Waghäusel		
		17	Haag	Julian	15.06.1990	0	n	TSV	Birkenau		
		16	Lenger	Dominik	07.05.1990	0	n	TSV	Birkenau		
		0	Feldmeyer	Moritz	05.05.1990	0	0	TV	Bad Rappenau		
		1	Püschel	Pascal	01.04.1990	0	N	Fort	Schwetzingen		
		19	Schmidt	Nico	19.02.1990	0	N	SpVgg	Ketsch		
		21	Rahn	Malte	01.01.1990	0	N	SpVgg	Ketsch		
		4	Fischer	Mirko		0	S		 Sportfreunde Neusatz-Bad Herrenalb		
1	x	1	Mathes	Stefan	22.09.1988	0	N	TV	Waldhof-Mhm
2	x	5	Schmitt	Fabian	20.01.1989	1	N	BC	Viernheim
3	x	3	König	Manuel	27.10.1988	0	N	TSG	Wiesloch
4	x	6	Lam	Patrick	09.12.1989	1	N	BC	Viernheim
5	x	neu	Minas	Felix	22.11.1988			TV	Mosbach
6	x	neu	Wukkert	Sergey	09.03.1989			TV	Mosbach
7	x	neu	Ries	Alexander	14.04.1988			TSG	Wiesloch
8	x	neu	Hofmann	David	18.10.1988			TV	Neckarau
9	x	neu	Miermeister	Patrick	02.09.1988			TV	Waldhof-Mhm
10	x	neu	Henninger	Nils	05.09.1989			SV	Leingarten
11	x	neu	Braun	Alexander	11.07.1989			SV	Leingarten
12	x	neu	Reither	Michael	05.05.1989			BC	Viernheim
13	x	neu	Emmler	Timo	22.06.1989			SG	Hemsbach
14	x		Reinemuth	Patrick	0.0.1988			SG	Hemsbach
15	x		Wieg	Patrick	16.12.1989			SG	Hemsbach
16	x		Brand	Tobias	15.08.1989			TV	Ma-Waldhof
17	x		Greis	Sascha	26.07.1989			TV	Ma-Waldhof
18	x		Rupprecht	Philipp	07.06.1989			TV	Ma-Waldhof
19	x		Wieg	Stephen	12.09.1988			SG	Hemsbach
20	x		Helmes	Markus	17.06.1988			BC	Viernheim
21	x		Winkenbach	Michael	23.04.1988			BC	Viernheim
22	x		Haas	Patrick	10.02.1988			TSG	Wiesloch
		neu	Dirwald	Daniel	20.06.1988			F96	Schwetzingen
		neu	Baum	Tobias	01.11.1989			TV	Waldhof-Mhm
		neu	Cook	Morris	31.12.1988			TV	Waldhof-Mhm
		2	Armbrüster	Tobias	26.02.1988	0	S		BV Rastatt
		5	Heiler	Daniel	27.07.1988	0	S		SSV Waghäusel
		3	Mai	Christian	08.08.1988	0	S		BC Schöllbronn
		4	Sickinger	Joachim	05.10.1988	0	S		SSV Waghäusel
		1	Draxlbauer	Stefan	25.11.1988	0	S		TSG Bruchsal
		6	Karcher	Thomas	08.12.1988	0	S		BC Schöllbronn
		2	Müller	Tobias	14.12.1988	0	N	TV	Bad Rappenau
		13	Kühner	Jens	13.01.1989	1	S		TSG Bruchsal
		0	Stadtler	Sebastian	17.03.1989	1	S	SSV	SSV Waghäusel
		8	Röckinger	Johannes	24.03.1989	1	S		TV Pforzheim
		0	Miltner	Benjamin	17.04.1989	1	N	TSG	Dossenheim
		4	Kippschull	Oliver	08.05.1989	1	N	TSG	Heilbronn
		12	Zwierzynski	Stephan	22.06.1989	1	S		TSG Bruchsal
		0	Frey	Sebastian	27.06.1989	1	N	TV	Waldhof
		11	Schäfer	Marco	28.06.1989	1	S		 Sportfreunde Neusatz-Bad Herrenalb
		7	Rieger	Noah	03.08.1989	1	S		TV Pforzheim
		8	Sokolov	Michael	05.08.1989	1	N	BC	Viernheim
		10	Gempp	Manuel	10.08.1989	1	S		Sportfreunde Neusatz-Bad Herrenalb
		9	Herm	Daniel	19.08.1989	1	S		SSV Waghäusel
		10	Bienert	Dominik	11.09.1989	1	N	TSV	Birkenau
		9	Thöne	Fabian	23.09.1989	1	N	F96	Schwetzingen
		7	Wiek	Patrick	16.12.1989	1	N	SG	Hemsbach
		11	von Toukas	Jorgo		1	N	TSG	Wiesloch
	x	1	Fürstenau	Moritz	08.12.1986	0	N	TSG	Wiesloch
	x	8	Orth	Sascha	03.08.1987	1	N	F96	Schwetzingen
	x	6	Weiss	Christian	23.10.1986	0	N	TSG	Dossenheim
	x	13	Altendorf	Michael	08.12.1987	1	N	SG	Hemsbach
	x	11	Kennel	Peter	04.02.1987	1	N	TSG	Wiesloch
	x	neu	Thalwieser	Fabian	20.04.1987			TV	Mosbach
	x	14	Blumenthal	David	26.09.1987	1	N	TSG	Wiesloch
	x	12	Avanzini	Manuel	06.11.1987	1	N	FC	Rot
	x	3	Schmitt	Wolfgang	30.12.1986	0	N	BC	Viernheim
		10	Müller	Stefan	19.07.1987	1	N	SG	Hemsbach
		6	Götz	Lucas	11.11.1987	1	S		BV Rastatt
		5	Mackert	Jochen	19.10.1987	1	S		Ettlinger SV
		0	Weil	Frederik	10.08.1987	1	N	TSG	Heilbronn
		15	Gruber 	Sebastian	26.07.1987	1	N	SG	Hemsbach
		0	Bock	Stefan	12.07.1987	1	N	Fort	Schwetzingen
		7	Hör	Simon	06.06.1987	1	S		BV Rastatt
		0	Boronowski	Markus	05.05.1987	1	N	1. BC	Viernheim
		9	Morozov	Alexander	07.04.1987	1	N	TSG	Heilbronn
		0	Rank	Christopher	25.03.1987	1	N	TV	Lauffen
		7	Waldvogel	Daniel	24.12.1986	0	N	TV	Bad Rappenau
		2	Püschel	Marcel	08.12.1986	0	N	Fort	Schwetzingen
		2	Busch	Patrick	18.11.1986	0	S	BV Rastatt	
		4	Wallmeier	Philip	18.11.1986	0	N	TSG	Wiesloch
		5	Wandtke	Timo	05.10.1986	0	N	TV	Bad Rappenau
		0	Miltner	Simon	25.09.1986	0	N	TSG	Dossenheim
		1	Gärtner	Michael	11.05.1986	0	S	TGS	Pforzheim
		0	Feldmeyer	Nils	12.04.1986	0	N	TV	Bad Rappenau
		0	Kron	Konstantin	87	0	S		Spfr. Neusatz
		3	Müller	Fabian		?	S	TV Busenbach	
		4	Schwab	Martin		?	S	TV Busenbach	
